version: "3.7"

services:
 app:
  image: node:12-alpine
  command: sh -c "yarn install && yarn run dev"
  ports:
   - target: 3000
     published: 3001
     protocol: tcp
     mode: host
  working_dir: /app
  volumes:
   - ./:/app
  environment:
   MYSQL_HOST: mydb
   MYSQL_USER: root
   MYSQL_PASSWORD: secret
   MYSQL_DB: todos
 mydb:
  image: mysql:5.7
  volumes:
   - todo-mysql-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: secret
   MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:           # 선언되있지 않은 volume 선언해주는 라인